config/routes.rb
AuthorizationApp::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }

  resources :launchpad, only: [:index, :show]
  
  root 'static_pages#home'

  

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :domains	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attr_accessible :email, :password, :password_confirmation, :remember_me, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery # with: :exception
end

app/controllers/launchpad_controller.rb
class LaunchpadController < ApplicationController
	def index
		# если пользователь забыл, какие домены для него доступны, то возможны два варианта развития событий:
		if current_user.domains.count < 3
			# у пользователя лишь два дозволенных домена: launchpad и %domain_name%, причем %domain_name%
			# всегда является вторым
			current_url = request.url.split(".")
			current_url.collect! do |i|
				(i == "launchpad") ? i = current_user.domains.all.second.domain : i
			end
			new_url = current_url.join(".")
			redirect_to new_url
		else
			# пользователю принадлежит множество доступных доменов и в таком случае пользователя перекидывает
			# на страницу со списком доступных ему доменов
			redirect_to :action => "show", :id => 1
		end
	end

	def show
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	def new
		super
	end

	def create
		build_resource(sign_up_params)

    if resource.save
    	yield resource if block_given?
    	if resource.active_for_authentication?
    	  set_flash_message :notice, :signed_up if is_flashing_format?
    	  sign_up(resource_name, resource)
    	  current_user.domains.create(domain: "launchpad")
    	  respond_with resource, location: after_sign_up_path_for(resource)
    	else
    	  set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
    	  expire_data_after_sign_in!
    	  respond_with resource, location: after_inactive_sign_up_path_for(resource)
    	end
    	else
    	  clean_up_passwords resource
    	  respond_with resource
    	end
			
	end

	def edit
		super
	end

	def update
		super
	end

	def destroy
		super
	end

	def cancel
		super
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

	include SessionsHelper

	def new
		super
	end

	def create
		@use = User.find_by_email(params[:user][:email])
		unless check_domain(@use)
			redirect_to root_path, :notice => "You haven't access to this domain!" 
			return
		end
		self.resource = warden.authenticate!(auth_options)
    	set_flash_message(:notice, :signed_in) if is_flashing_format?
    	sign_in(resource_name, resource)
    	yield resource if block_given?
    	respond_with resource, location: after_sign_in_path_for(resource)
	end

	def destroy
		super
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/launchpad_helper.rb
module LaunchpadHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def check_domain(user)
			current_domain = request.env['HTTP_HOST'].split('.').first
			#предполагается, что в модели пользователя существует атрибут domain
			user.domains.each do |d|
				return true if d.domain == current_domain
			end
			return false
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/launchpad/index.html.erb
<h1>Launchpad home page</h1>

app/views/launchpad/show.html.erb
<h1>Available domains' list</h1>
<body>
	<%= current_user.email %></br>
	Domains' list:</br>
	<% current_user.domains.all.each do |domain| %>
		&nbsp;&nbsp;&nbsp;<%= domain.domain %></br>
	<% end %>
</body>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<% if user_signed_in? %>
		Logged in as <%= current_user.email %>.
		<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
		<li><%= link_to "Edit profile", edit_user_registration_path %></li>
		<li><%= link_to "Forgot available domains?", launchpad_index_path %></li>
	<% else %>
		<li><%= link_to "Sign up", new_user_registration_path %></li>
		<li><%= link_to "Sign in", new_user_session_path %></li>
	<% end %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthorizationApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<div id="user_nav">
			<% flash.each do |name, msg| %>
			        <%= content_tag :div, msg, id: "flash_#{name}" %>
			<% end %>
			
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</div>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<body>List of users:
	<ul class="users">
		<% User.all.each do |u| %>
			<b><%= u.email %></b></br>
			Domain's list:</br>
			<% if u.domains.count != nil %>
				<% u.domains.all.each do |d| %>
					&nbsp;&nbsp;&nbsp;<%= d.domain %></br>
				<% end %>
			<% end %>
		<% end %>
	</ul>
</body>